import turtle
h = turtle.Turtle()
h.up()
h.backward(245)
def house():
  number = int(input("# of Houses: "))
  i = 0
  while i < number:
    length = int(input("Length: "))
    height = int(input("Height: "))
    hc = input("House Color: ")
    dh = int(input("Door Height: "))
    dw = int(input("Door Width: "))
    dc = input("Door Color: ")
    distance = (length / 2) - (dw /2)
    chimney = input("Is there a chimeny (y/n): ")
    if chimney == "y":
      ch = int(input("Chimney Height: "))
      cw = int(input("Chimney Width: "))
      cd = ch - (cw * (3 ** .5))
      cc = input("Chimeny Color: ")
    h.down()
    h.fillcolor(hc)
    h.begin_fill()
    h.forward(length)
    h.left(90)
    h.forward(height)
    h.left(30)
    h.forward(length)
    h.left(120)
    h.forward(length)
    h.left(120)
    h.forward(length)
    h.left(180)
    h.forward(length)
    h.left(90)
    h.forward(height)
    h.left(90)
    h.end_fill()
    h.forward(distance)
    h.left(90)
    h.fillcolor(dc)
    h.begin_fill()
    h.forward(dh)
    h.right(90)
    h.forward(dw)
    h.right(90)
    h.forward(dh)
    h.right(90)
    h.forward(dw)
    h.end_fill()
    h.right(180)
    h.forward(dw)
    if chimney == "y":
      h.fillcolor(cc)
      h.right(180)
      h.forward(dw)
      h.forward(distance)
      h.right(90)
      h.forward(height)
      h.begin_fill()
      h.forward(ch)
      h.right(90)
      h.forward(cw)
      h.right(90)
      h.forward(cd)
      h.right(30)
      h.forward(2*cw)
      h.left(30)
      h.end_fill()
      h.forward(height)
      h.left(90)
      h.forward(distance)
      h.forward(dw)
    h.up()
    a = distance + 20
    h.forward(a)
    i += 1
house()